apiVersion: v1
kind: Pod
metadata:
  name: testpod
  annotations:
    description: this is my 1st pod
  
spec:
  containers:
    - name: c02
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]
  restartPolicy: Never         # Defaults to Always