apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: mylivenessprobe
spec:
  containers:
  - name: liveness
    image: ubuntu
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:      
      exec:
        command:     
        - cat       
        - /tmp/healthy
      initialDelaySeconds: 5 
      periodSeconds: 5      
      timeoutSeconds: 30