# Install metrics server
#kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # deployment name
spec:                     # start Replica template
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:             # start pod template
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

## apply auto_scaling
# kubectl autoscale deployment nginx-deployment --cpu-percent=20 --min=1 --max=10
