apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: pod-1
spec:
  containers:
  - name: container-1
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo Hello-Raghav; sleep 5 ; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    name: pod-2
spec:
  containers:
  - name: container-1
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
